### ISSUE TITLE
fix : hikariCP의 driver-class-name property에 mariadb Driver 연결 안됨

### ISSUE THREAD

**Issue by kimhanui** [kimhanui/Login-SG#6]
## Bug
- hikariCP의 driver-class-name property에 mariadb Driver 연결 안됨
  ```
  spring:
    profiles:
      active: local
    datasource:
      hikari:
        driver-class-name: org.mariadb.jdbc.Driver
        username: -
        password: -
        jdbc-url: -
  ```
- hikari 제거 후 정상 빌드 됨
  ```
  spring:
    profiles:
      active: local
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: -
      password: -
      url: -
  ```

사용 환경
- spring boot : 2.6.1
- hikariCP: 4.0.3
- docker image property: MARIADB_VERSION=1:10.6.5+maria~focal
- OS: Window 10 pro

## Log
```
Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles local are currently active).


Process finished with exit code 1
```
